#pragma once

#define VERSION 1
#define SUB_VERSION 2
#define WIP_VERSION 0

#define FILE_VERSION        VERSION.SUB_VERSION.WIP_VERSION
#define PRODUCT_VERSION     VERSION.SUB_VERSION.WIP_VERSION

#define TO_STRING(a) #a
#define _VerJoin(a, b, c)  TO_STRING(a.b.c)  

#define FILE_VERSION_STR _VerJoin(VERSION,SUB_VERSION,WIP_VERSION)
#define PRODUCT_VERSION_STR _VerJoin(VERSION,SUB_VERSION,WIP_VERSION)
